/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.17.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.api;

import org.openapitools.model.ConnexionPostRequest;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;

import io.swagger.v3.oas.annotations.responses.ApiResponse;

import io.swagger.v3.oas.annotations.tags.Tag;

import org.springframework.http.HttpStatus;

import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;

import java.util.Optional;
import jakarta.annotation.Generated;

import jakarta.validation.Valid;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-11-14T21:47:29.555388808Z[Africa/Dakar]", comments = "Generator version: 7.17.0")
@Validated
@Tag(name = "Authentification", description = "the Authentification API")
public interface ConnexionApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    String PATH_CONNEXION_POST = "/connexion";
    /**
     * POST /connexion : Connexion d&#39;un utilisateur
     *
     * @param connexionPostRequest  (required)
     * @return Connexion réussie (status code 200)
     *         or Identifiants invalides (status code 401)
     */
    @Operation(
        operationId = "connexionPost",
        summary = "Connexion d'un utilisateur",
        tags = { "Authentification" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Connexion réussie"),
            @ApiResponse(responseCode = "401", description = "Identifiants invalides")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ConnexionApi.PATH_CONNEXION_POST,
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> connexionPost(
        @Parameter(name = "ConnexionPostRequest", description = "", required = true) @Valid @RequestBody ConnexionPostRequest connexionPostRequest
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
