/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.17.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.api;

import org.openapitools.model.InscriptionPostRequest;
import org.openapitools.model.Utilisateur;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;

import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;

import io.swagger.v3.oas.annotations.tags.Tag;

import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;




import java.util.Optional;

import jakarta.annotation.Generated;

import jakarta.validation.Valid;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-11-14T21:47:29.555388808Z[Africa/Dakar]", comments = "Generator version: 7.17.0")
@Validated
@Tag(name = "Authentification", description = "the Authentification API")
public interface InscriptionApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    String PATH_INSCRIPTION_POST = "/inscription";
    /**
     * POST /inscription : Inscription d&#39;un utilisateur (Étudiant ou Alumni)
     *
     * @param inscriptionPostRequest  (required)
     * @return Utilisateur créé - Code envoyé (status code 201)
     *         or Données invalides (status code 400)
     */
    @Operation(
        operationId = "inscriptionPost",
        summary = "Inscription d'un utilisateur (Étudiant ou Alumni)",
        tags = { "Authentification" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Utilisateur créé - Code envoyé", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Utilisateur.class))
            }),
            @ApiResponse(responseCode = "400", description = "Données invalides")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = InscriptionApi.PATH_INSCRIPTION_POST,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Utilisateur> inscriptionPost(
        @Parameter(name = "InscriptionPostRequest", description = "", required = true) @Valid @RequestBody InscriptionPostRequest inscriptionPostRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"role\" : { \"libelle\" : \"ALUMNI\", \"id\" : 1 }, \"dateNaissance\" : \"2000-01-23\", \"codeExpiration\" : true, \"telephone\" : \"telephone\", \"sexe\" : \"M\", \"actif\" : false, \"codeValidation\" : \"482915\", \"nom\" : \"nom\", \"password\" : \"password\", \"id\" : 0, \"prenom\" : \"prenom\", \"email\" : \"email\", \"username\" : \"username\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
