/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.17.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package uasz.alumni.ms_cv.controllers;

import uasz.alumni.ms_cv.models.Certification;
import uasz.alumni.ms_cv.models.CertificationCreate;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-11-26T15:28:11.703869118Z[Africa/Dakar]", comments = "Generator version: 7.17.0")
@Validated
@Tag(name = "Certifications", description = "the Certifications API")
public interface CertificationsApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    String PATH_CERTIFICATIONS_ID_DELETE = "/certifications/{id}";
    /**
     * DELETE /certifications/{id} : Supprimer une certification
     *
     * @param id  (required)
     * @return Certification supprimée (status code 204)
     */
    @Operation(
        operationId = "certificationsIdDelete",
        summary = "Supprimer une certification",
        tags = { "Certifications" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Certification supprimée")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = CertificationsApi.PATH_CERTIFICATIONS_ID_DELETE
    )
    default ResponseEntity<Void> certificationsIdDelete(
        @NotNull @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Integer id
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_CERTIFICATIONS_ID_PUT = "/certifications/{id}";
    /**
     * PUT /certifications/{id} : Modifier une certification
     *
     * @param id  (required)
     * @param certificationCreate  (required)
     * @return Certification mise à jour (status code 200)
     */
    @Operation(
        operationId = "certificationsIdPut",
        summary = "Modifier une certification",
        tags = { "Certifications" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Certification mise à jour")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = CertificationsApi.PATH_CERTIFICATIONS_ID_PUT,
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> certificationsIdPut(
        @NotNull @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Integer id,
        @Parameter(name = "CertificationCreate", description = "", required = true) @Valid @RequestBody CertificationCreate certificationCreate
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_CERTIFICATIONS_POST = "/certifications";
    /**
     * POST /certifications : Ajouter une certification
     *
     * @param certificationCreate  (required)
     * @return Certification ajoutée (status code 201)
     */
    @Operation(
        operationId = "certificationsPost",
        summary = "Ajouter une certification",
        tags = { "Certifications" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Certification ajoutée", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Certification.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = CertificationsApi.PATH_CERTIFICATIONS_POST,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Certification> certificationsPost(
        @Parameter(name = "CertificationCreate", description = "", required = true) @Valid @RequestBody CertificationCreate certificationCreate
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"cvId\" : 1, \"lienCredential\" : \"https://aws.amazon.com/verification/12345\", \"dateExpiration\" : \"2025-03-15\", \"organisme\" : \"Amazon Web Services\", \"dateObtention\" : \"2022-03-15\", \"id\" : 1, \"nom\" : \"AWS Certified Developer\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
