/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.17.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.api;

import org.openapitools.model.Role;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;

import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;

import io.swagger.v3.oas.annotations.tags.Tag;

import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;



import java.util.List;

import java.util.Optional;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-11-14T21:47:29.555388808Z[Africa/Dakar]", comments = "Generator version: 7.17.0")
@Validated
@Tag(name = "Rôles", description = "the Rôles API")
public interface RolesApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    String PATH_ROLES_GET = "/roles";
    /**
     * GET /roles : Liste des rôles
     *
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "rolesGet",
        summary = "Liste des rôles",
        tags = { "Rôles" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Role.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = RolesApi.PATH_ROLES_GET,
        produces = { "application/json" }
    )
    default ResponseEntity<List<Role>> rolesGet(
        
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"libelle\" : \"ALUMNI\", \"id\" : 1 }, { \"libelle\" : \"ALUMNI\", \"id\" : 1 } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_ROLES_POST = "/roles";
    /**
     * POST /roles : Ajouter un rôle
     *
     * @param role  (required)
     * @return Créé (status code 201)
     */
    @Operation(
        operationId = "rolesPost",
        summary = "Ajouter un rôle",
        tags = { "Rôles" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Créé", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Role.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = RolesApi.PATH_ROLES_POST,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Role> rolesPost(
        @Parameter(name = "Role", description = "", required = true) @Valid @RequestBody Role role
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"libelle\" : \"ALUMNI\", \"id\" : 1 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
