/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.17.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.api;

import org.openapitools.model.ValidationCodePostRequest;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;

import io.swagger.v3.oas.annotations.responses.ApiResponse;

import io.swagger.v3.oas.annotations.tags.Tag;

import org.springframework.http.HttpStatus;

import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;

import java.util.Optional;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-11-14T21:47:29.555388808Z[Africa/Dakar]", comments = "Generator version: 7.17.0")
@Validated
@Tag(name = "Authentification", description = "the Authentification API")
public interface ValidationCodeApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    String PATH_VALIDATION_CODE_POST = "/validation-code";
    /**
     * POST /validation-code : Validation du code
     *
     * @param validationCodePostRequest  (required)
     * @return Compte activé (status code 200)
     *         or Code invalide ou expiré (status code 400)
     */
    @Operation(
        operationId = "validationCodePost",
        summary = "Validation du code",
        tags = { "Authentification" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Compte activé"),
            @ApiResponse(responseCode = "400", description = "Code invalide ou expiré")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ValidationCodeApi.PATH_VALIDATION_CODE_POST,
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> validationCodePost(
        @Parameter(name = "ValidationCodePostRequest", description = "", required = true) @Valid @RequestBody ValidationCodePostRequest validationCodePostRequest
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
